### ISSUE TITLE
win8.1导入提示cmroute.dll找不到模块

### ISSUE THREAD

**Issue by cloudslsw** [sabersalv/freedom-routes#10]
然后我从网上下载了好几个版本的cmroute.dll，64位和32位的都试了，还是一样的错误，希望大大能看下什么原因

**Comment by sabersalv** [comment]
下载https://raw.githubusercontent.com/sabersalv/freedom-routes/dist/windows.zip 解压出来不是有个cmroute.dll 么？

**Comment by sabersalv** [comment]
你把cmroute.dll拷贝到`C:\Windows\system32`下面试试

**Comment by cloudslsw** [comment]
是的，自带有，但是拷贝到系统system32也不行，还是提示“启动cmroute.dll出现问题，找不到指定模块”

**Comment by sabersalv** [comment]
有很多原因, 一般只要cmroutes.dll和运行这个脚本在同一目录就可已了, 我需要更详细信息才能判断。

1. 修改routes-up.bat：　把 `@echo off`改成`@echo on`
2. 右键管理员运行
3. 把结果截图发上来看看

**Comment by cloudslsw** [comment]
![qqss20160109185659](https://cloud.githubusercontent.com/assets/11231847/12215733/0d65e12c-b704-11e5-8edc-237f902874b1.JPG)

**Comment by sabersalv** [comment]
我修改了一下https://github.com/sabersalv/freedom-routes/commit/157d52544be794ceb27fdb4df773874b158c11d1
应该修复了。　你重新下载后再试试。不行的话再截图一下

**Comment by cloudslsw** [comment]
谢谢大大，修复了，ありがとう
