### ISSUE TITLE
win10如何实现永久添加路由表

### ISSUE THREAD

**Issue by lianmw** [sabersalv/freedom-routes#11]

**Comment by sabersalv** [comment]
随便搜索了一下 http://jingyan.baidu.com/article/455a9950e9f2e3a167277872.html

**Comment by lianmw** [comment]
我试过在哪个add.txt文件里替换add到add -p，没成功 = =
之前哪个修改路由表脚本到是可以，新的这个有办法实现么

**Comment by sabersalv** [comment]
新版的应该不行, 我给你单独弄一个加`-p`的老版本的文件吧。

**Comment by sabersalv** [comment]
已更新，永久版下载地址https://github.com/sabersalv/freedom-routes/blob/dist/windows-permanent.zip

**Comment by lianmw** [comment]
= =   辛苦了，不过这个自己动动手就可以了，还是谢谢了，这东西对于自己折腾搭vpn玩游戏的太好用了      感谢感谢

**Comment by lianmw** [comment]
{{range $i, $ip := .Ips}}add {{$ip.Ip}} mask {{$ip.Mask}} default METRIC default IF default
{{end}}

我在那个模板里看到add.TXT文件是这个，虽然不太明白是啥，感觉是不是修改这个命令就可以了？

**Comment by sabersalv** [comment]
这是一个Go语言写的程序， 它运行后会根据模板生成add.txt等文件, 我把这个程序部署到自己的服务器里面,
这样它就每天自动运行一次，把生成的文件上传上去，然后你们就可以直接下载生成好的文件, 而不用再本地运行Go程序了.

是的, 只要修改模板并且发Pull Requst过来, 就可以了。

**Comment by sabersalv** [comment]
当然你也可以下载这个Go程序，并且在本地运行
https://github.com/sabersalv/freedom-routes/blob/master/docs/local.md

2016-01-08 18:06 GMT+08:00 Saber Salv <sabersalv@gmail.com>:

> 这是一个Go语言写的程序， 它运行后会根据模板生成add.txt等文件, 我把这个程序部署到自己的服务器里面,
> 这样它就每天自动运行一次，把生成的文件上传上去，然后你们就可以直接下载生成好的文件, 而不用再本地运行Go程序了.
>
> 是的, 只要修改模板并且发Pull Requst过来, 就可以了。
>

**Comment by lianmw** [comment]
好的，我去看看，哈哈    竟然被我猜对了

**Comment by lianmw** [comment]
github不太会用，我就是找这个路由表才发现的，那个pull requst不懂什么意思，那会瞎点了点，不知道会不会给你那页面有啥影响 = =

**Comment by sabersalv** [comment]
没事, 就是你写点代码合并到我这里来。不会也不影响。

2016-01-08 23:39 GMT+08:00 lianmw <notifications@github.com>:
