### ISSUE TITLE
最新的永久版bat错误

### ISSUE THREAD

**Issue by ycj652901** [sabersalv/freedom-routes#12]
我下载下来最新的永久版的2个bat,管理员运行后显示 

系统找不到指定的文件。
'*' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by sabersalv** [comment]
你重新下载一下, 应该修复了。没有的话重开这个issue
