### ISSUE TITLE
路由表如何用于anyconnect

### ISSUE THREAD

**Issue by lianmw** [sabersalv/freedom-routes#13]
我又来打扰了。。。刚弄个anyconnect，连上以后全局走代理，电脑上打的路由表没效果，得怎么弄啊

**Comment by sabersalv** [comment]
anyconnect是什么东西呀, 我不知道呀

**Comment by lianmw** [comment]
额，，思科anyconnect  vpn协议，我后来百度到了用no route规则可以 = =

**Comment by sabersalv** [comment]
不太懂, 你自己解决了? 那你关闭一下这个Issue.
