### ISSUE TITLE
WIN10 运行永久性bat

### ISSUE THREAD

**Issue by ycj652901** [sabersalv/freedom-routes#14]
我新装的WIN10 运行永久版的bat 后 在重启 的时候会等待3分钟左右 系统一直在转圈....找了半天才发现是这个原因...SO...这要如何解决...每次开机都要等个3分钟..好煎熬

**Comment by chinapengwei** [comment]
我在openwrt中pptp按文中方法设置，成功分流，但访问如twitter等网站则不行，traceroute了是可以找到的，但在google浏览器中则无法访问，我的VPN之前播号pptp上去是可以正常访问twitter的，不知如何解决。

**Comment by sabersalv** [comment]
@ycj652901 
不要用永久版本, 用快速的那个版本 windows.zip

@chinapengwei 
用Chrome的DevTools分析下
