### ISSUE TITLE
问下，网络版本是给服务器用的吗？

### ISSUE THREAD

**Issue by LightSofa** [SaberSalv/freedom-routes#4]

**Comment by XiaoluD** [comment]
好像这个路径给的不对，在mac下无法用啊。
PPTP
cp routes-up.sh /etc/ppp/ip-pre-up
cp routes-down.sh /etc/ppp/ip-down.d/ip-down

**Comment by SaberSalv** [comment]
@XiaoluD 

在mac我没测试过, 不行的话, 你可以手动运行一下 `$ sudo ./routes-up.sh`
